// SOCKET
export const SET_SOCKET = 'SET_SOCKET';
export const LOAD_INTERLOCUTORS = 'SET_INTERLOCUTORS';
export const LOAD_BOTS = 'LOAD_BOTS';

// APP
export const SHOW_ONLINE_USERS = 'SHOW_ONLINE_USERS';
export const SET_CURRENT_INTERLOCUTOR = 'SET_CURRENT_INTERLOCUTOR';
export const SET_SEARCH_INTERLOCUTORS = 'SET_FILTER_USERNAMES';

// MESSAGES
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
