// SOCKET
export const SET_SOCKET = 'SET_SOCKET';
export const LOAD_INTERLOCUTORS = 'SET_INTERLOCUTORS';

// APP
export const SHOW_ONLINE_USERS = 'SHOW_ONLINE_USERS';
export const SET_CURRENT_INTERLOCUTOR = 'SET_CURRENT_INTERLOCUTOR';
